In [1]:
l = [1, 2, 3, [4, 5]]
l1 = l.copy()
l1[1] = 6
print(l, l1)


[1, 2, 3, [4, 5]] [1, 6, 3, [4, 5]]


shallow copy is same as copy.copy(). This is the second method of "copying a list". While the first method is to just assign a list to a new variable. In this case, the new variable is just a reference to the old list. So, if you change the new list, the old list will also change and vice versa. The shallow copy is similar to the first method ie assignment.In shallow copy, just like te assignment type, creates a new object and fills with the references of the original copy. Normal changes like adding removing etc of the original list won't affect the other copy in a shallow list. But if changes are made to the inner lists etc, in the shallow copy or the original copy, then the changes done for the first list will be reflected in the second list as well, viceversa.

shallow copy (copy.copy) contradicts with the name, the changes in the inner lists gets reflected in the original one. But not the changes in the actual list. In hard copy or deep copy, it is quite ""hard" in handling, ie any change in the deep cpy will not affect the original copy

In [4]:
import copy
original = [1, 2, [3, 4]]
original_assign=original
print(original,original_assign)
shallow_copy = copy.copy(original)
print(original,original_assign)
shallow_copy[2][0] = 5
print(original,original_assign, shallow_copy)  # Outputs: [1, 2, [5, 4]]

[1, 2, [3, 4]] [1, 2, [3, 4]]
[1, 2, [3, 4]] [1, 2, [3, 4]]
[1, 2, [5, 4]] [1, 2, [5, 4]] [1, 2, [5, 4]]


In [1]:
import copy
original = [1, 2, [3, 4]]
original_assign=original
print(original,original_assign)
shallow_copy = copy.copy(original)
print(original,original_assign)
shallow_copy[1] = 50
print(original,original_assign, shallow_copy)  # Outputs: [1, 2, [5, 4]]

[1, 2, [3, 4]] [1, 2, [3, 4]]
[1, 2, [3, 4]] [1, 2, [3, 4]]
[1, 2, [3, 4]] [1, 2, [3, 4]] [1, 50, [3, 4]]


In [10]:
import copy
original = [1, 2, [3, 4]]
original_assign=original
print(original,original_assign)
shallow_copy = copy.copy(original)
print(original,original_assign, shallow_copy)
original_assign[2] = 100
print(original,original_assign, shallow_copy)  # Outputs: [1, 2, [5, 4]]
shallow_copy[2][0] = 50
print(original,original_assign, shallow_copy) 

[1, 2, [3, 4]] [1, 2, [3, 4]]
[1, 2, [3, 4]] [1, 2, [3, 4]] [1, 2, [3, 4]]
[1, 2, 100] [1, 2, 100] [1, 2, [3, 4]]
[1, 2, 100] [1, 2, 100] [1, 2, [50, 4]]


In [237]:
import copy
original = [1, 2, [3, 4]]
deep_copy = copy.deepcopy(original)
print(deep_copy, original)
deep_copy[2][0]=25
deep_copy.append(50)
print(deep_copy, original)

[1, 2, [3, 4]] [1, 2, [3, 4]]
[1, 2, [25, 4], 50] [1, 2, [3, 4]]


in deep copy, the elements are recursively added to the new variable and not the references to the original element. Hence both the copies remain intact. 

In [10]:

import copy
l = [1, 2, 3, [4, 5]]
l1 = copy.deepcopy(l)
print(id(l1[1]), id(l[1]))
l1[1] = 6
print(l, l1)
print(id(l1[1]), id(l[1]))

4413393280 4413393280
[1, 2, 3, [4, 5]] [1, 6, 3, [4, 5]]
4413393408 4413393280


In [ ]:
l = [1, 2, 3, [4, 5]]
l2 = copy.copy(l)
print(id(l2[1]), id(l[1]))
l2[1] = 6
print(l, l2)
print(id(l2[1]), id(l[1]))


4413393280 4413393280
[1, 2, 3, [4, 5]] [1, 6, 3, [4, 5]]
4413393408 4413393280


In [81]:
a = "abcd"
print(list(map(str,a)))
print(list(map(list,a)))
print(list(a))
b=[1,3,2,4]
print ([[x] for x in b])
d=[[x] for x in b]
d

['a', 'b', 'c', 'd']
[['a'], ['b'], ['c'], ['d']]
['a', 'b', 'c', 'd']
[[1], [3], [2], [4]]


[[1], [3], [2], [4]]

In [9]:
var = 454
while(not(var)):
   print("inside not var")
   var**=2
   print(var)
else:
   var//=2
   print("Inside", var)
print(var)


var=527





Inside 227
227


In [6]:
var=526
while var:
    
    r=var%10
    print (var, r)
    var=var//10
print ("out of the loop with remainder is {} and var as {} ".format(r, var))
    

526 6
52 2
5 5
out of the loop with remainder is 5 and var as 0 


In [10]:
sales = {
    'abc': 65,
    'xyz': 105
}
if sales['abc'] > 65:
    print("Full Incentive")
elif sales['xyz'] > 65:
    print("Lead")
elif sales['jkl'] > 65:
    print("Top Performer")
else :
    print("No results")

sales ={
    "abc":65,
    "xyz":105
}

if sales['abc']>=65:
    print("full incentive")
elif(sales['xyz']>65):
    print("Lead")
elif sales['jkl']>65:
    print("Top performer")
else:
    print ("No results")

Lead
full incentive


In [8]:
s="mnopqr"
i="m"
c=0
while (i in s) and (c<10):
    
    print(i,end=";")
    c+=1

print()
s="mnopqr"
i="m"
c=1
while (i in s ) and c<=10:
    print (i,end=";")
    c+=1

m;m;m;m;m;m;m;m;m;m;
m;m;m;m;m;m;m;m;m;m;

In [1]:
  #joining string with the separator in between
"abc".join("defgh"), "join".join("defghi")

('dabceabcfabcgabch', 'djoinejoinfjoingjoinhjoini')

In [5]:
l=['thisisa string',"another string"]
"".join(l), "|".join(l)

('thisisa stringanother string', 'thisisa string|another string')

In [214]:
string='dabceabcfabcgabch' #???
string.partition('c') #split split multiple times, but partition splits only once

('dab', 'c', 'eabcfabcgabch')

In [18]:
import numpy as np
l=[3, 2, -5, 1, 0, 3]
sums=np.sum(l)
sums #actually sum(l) also works, but due to overloading of sum function (by mistake) sum(l) does not work in this notebook

4

In [5]:
import numpy as np
l=[6, 2, 9, 1, -3, 5, 4]
#sum=np.sum(l)
sum=0
for i in l:
    sum=sum+ ((i-4)**2)
print(sum)    
s=[(x-4)**2 for x in l]
np.sum(s)

92


np.int64(92)

In [7]:
from functools import reduce
l=[3, 2, -5, 1, 0, 3]
l_sq=list(map(lambda x:x**2,l))
print(l_sq)
lsum=reduce(lambda a, b: a + b**2, l,0)
lsum, list(set(l)), reduce(lambda a,b:a+b, l,0), [x+1 for x in l if x>=0],np.sum([x**2 for x in l]), reduce(lambda a,b:a+b,l,0)


[9, 4, 25, 1, 0, 9]


(48, [0, 1, 2, 3, -5], 4, [4, 3, 2, 1, 4], np.int64(48), 4)

In [17]:
l=np.array(l)
simple_indexing=l[3]
simple_indexing, type(simple_indexing)

(1, numpy.int64)

In [18]:
fancy_indexing=l[[2,4]]
fancy_indexing, type(l)

(array([-5,  0]), numpy.ndarray)

In [52]:
import numpy as np
np.array(l).T

array([ 3,  2, -5,  1,  0,  3])

In [20]:
np.ones((2,3,5)) #3darray
np.ones((2,4)).T

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [67]:
l1[[0,1,0]]

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [71]:
l2=np.arange(1,21).reshape(4,5)
l2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [75]:
l2[[0,2,3]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [42]:


def square(l):
    print(l)
    return ([x**2 for x in l])

l=[3, 2, -5, 1, 0, 3]
l_sq= list(map(square,[l]))
l_sq, l[:3]

[3, 2, -5, 1, 0, 3]


([[9, 4, 25, 1, 0, 9]], [3, 2, -5])

In [49]:
def generate_permutations(lst): #???
    if len(lst) == 0:
        return [[]]
    if len(lst) == 1:
        return [lst]

    permutations = []
    for i in range(len(lst)):
        rest = lst[:i] + lst[i+1:]
        print("lst[i], lst[i+1:], rest and i are resp {}, {}, {} and {}  ".format(lst[i], lst[i+1:], rest,i))
        for p in generate_permutations(rest):
            print("p is "+ str(p))
            permutations.append([lst[i]] + p)
            print("lst[i] for i = {} is {} ".format (i, lst[i]))
    return permutations

# Example usage
my_list = [1, 2, 3 ]
permutations = generate_permutations(my_list)
#for permutation in permutations:
print(permutations)

lst[i], lst[i+1:], rest and i are resp 1, [2, 3], [2, 3] and 0  
lst[i], lst[i+1:], rest and i are resp 2, [3], [3] and 0  
p is [3]
lst[i] for i = 0 is 2 
lst[i], lst[i+1:], rest and i are resp 3, [], [2] and 1  
p is [2]
lst[i] for i = 1 is 3 
p is [2, 3]
lst[i] for i = 0 is 1 
p is [3, 2]
lst[i] for i = 0 is 1 
lst[i], lst[i+1:], rest and i are resp 2, [3], [1, 3] and 1  
lst[i], lst[i+1:], rest and i are resp 1, [3], [3] and 0  
p is [3]
lst[i] for i = 0 is 1 
lst[i], lst[i+1:], rest and i are resp 3, [], [1] and 1  
p is [1]
lst[i] for i = 1 is 3 
p is [1, 3]
lst[i] for i = 1 is 2 
p is [3, 1]
lst[i] for i = 1 is 2 
lst[i], lst[i+1:], rest and i are resp 3, [], [1, 2] and 2  
lst[i], lst[i+1:], rest and i are resp 1, [2], [2] and 0  
p is [2]
lst[i] for i = 0 is 1 
lst[i], lst[i+1:], rest and i are resp 2, [], [1] and 1  
p is [1]
lst[i] for i = 1 is 2 
p is [1, 2]
lst[i] for i = 2 is 3 
p is [2, 1]
lst[i] for i = 2 is 3 
[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3,

In [197]:
len(l_sort)//2
l_sort[3], l_sort


(7, [1, 2, 5, 7, 8, 9, 10, 24])

In [34]:
l_sort[(len(l_sort)//2) -1], l_sort[int(((len(l_sort)/2)))] #median from a given list

(7, 8)

In [36]:
int(((len(l_sort)/2)))

4

In [73]:
import numpy as np
import pandas as pd
l=[1,3,5, 5,2,7,0,10,16, 15]
l=np.array(l)
l.argsort()[::-1][:3], np.argsort(l)[::-1][:3], np.argmax(l), pd.Series(l).value_counts().index[0]
pd.Series(l).value_counts()

5     2
1     1
3     1
2     1
7     1
0     1
10    1
16    1
15    1
Name: count, dtype: int64

In [179]:
l=[1,3,5,2,7,0,10,16] #???
l=np.array(l)
print(l.argsort( ) [ -3: ][: : -1]) #To get the indices of 3 maximum values of the array
print(l.argsort( ) [ :3 ]) #To get the indices of 3 minimum values of the array; Default is ascending order sort

[7 6 4]
[5 0 3]


In [204]:
np.unique(l, return_counts=True) #counts of the elements of an array #???
np.unique(l,return_counts=True) #like counter

(array([ 0,  1,  2,  3,  5,  7, 10, 16]), array([1, 1, 1, 1, 1, 1, 1, 1]))

In [206]:
s=['a','b','a','b','c','d']
s=np.array(s)
np.unique(s,return_counts=True)

(array(['a', 'b', 'c', 'd'], dtype='<U1'), array([2, 2, 1, 1]))

In [187]:
l #??? 
np.array_split(l,5) #spliting of an array using numpy Array split will split the 5 into 5 small arrays of equal or unequal arrays

[array([1, 3]), array([5, 2]), array([7, 0]), array([10]), array([16])]

In [182]:
#???
a = np.array([[10, 4], [8, 12]])
b = np.array([[15, 6]])
c = np.concatenate((a, b), axis=0)
c

array([[10,  4],
       [ 8, 12],
       [15,  6]])

In [189]:
c[:,0], c[:,[0]] #extracting/slicing an array in an ndarray format ???

(array([10,  8, 15]),
 array([[10],
        [ 8],
        [15]]))

In [24]:
s="abc"
s.__contains__('a') #dunder methods require an instance to get invoked

True

In [25]:
np.char.join(",", s) #convert string to char array using numpy
np.char.join(",", s), ",".join(s)

(array('a,b,c', dtype='<U5'), 'a,b,c')

In [212]:
def fib(n):
    a,b=0,1
    
    while a < n: 
        yield a 
        a, b = b, a + b 

c=fib(5)

# Iterating over the generator object using next 
# In Python 3, __next__() 
# print(__next__(x))  
# print(__next__(x)) 
# print(__next__(x)) 
# print(__next__(x)) 
# print(__next__(x)) 

#There is some error related to __next__()

In [87]:
txt = "apple, banana, cherry"
print(list(txt))
# setting the maxsplit parameter to 1, will return a list with 2 elements! ???
x = txt.rsplit(", ",1)
print(x)
print ([x for x in list(txt)])
print("x[0],x[1]", x[0],x[1])
print(x[-1])
x = txt.rsplit(", ",2)
print(x, x[1])

['a', 'p', 'p', 'l', 'e', ',', ' ', 'b', 'a', 'n', 'a', 'n', 'a', ',', ' ', 'c', 'h', 'e', 'r', 'r', 'y']
['apple, banana', 'cherry']
['a', 'p', 'p', 'l', 'e', ',', ' ', 'b', 'a', 'n', 'a', 'n', 'a', ',', ' ', 'c', 'h', 'e', 'r', 'r', 'y']
x[0],x[1] apple, banana cherry
cherry
['apple', 'banana', 'cherry'] banana


In [27]:
string="abcd"
string_l=list(string)
string_l_str="".join(string_l)
string_l_str1=" ".join(string)
string_l, string_l_str, string_l_str1

(['a', 'b', 'c', 'd'], 'abcd', 'a b c d')

In [78]:
import numpy as np
a=list(np.arange(1,20))
print(a)
b=[(2*x)+1 for x in a]
a,b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39])